{% set name = "ltd-conveyor" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fd9df7853b9ec28b89da35d9484209fd97d2b26e7a80a3cc7511bd7be9176ee6

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - ltd = ltdconveyor.cli.main:main

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python >=3.7
    - setuptools_scm
    - boto3
    - requests
    - uritemplate
    - click

test:
  commands:
    - ltd --version
    - ltd --help
    - ltd upload --help

about:
  home: https://github.com/lsst-sqre/ltd-conveyor
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Conveyor command-line app for LSST the Docs (LTD) services and clients.
  # The remaining entries in this section are optional, but recommended.
  description: |
    LSST the Docs (LTD) is a scalable service for hosting versioned static
    documentation projects that was originally built for the Vera C. Rubin
    Observatory. LTD Conveyor is the command-line client for uploading
    documentation builds and administering an LTD deployment.
  doc_url: https://ltd-conveyor.lsst.io/
  dev_url: https://github.com/lsst-sqre/ltd-conveyor

extra:
  recipe-maintainers:
    - jonathansick
